---
title: "Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries
```{r}
library(ggplot2)
library(brms)
library(brmstools)

```


## DATA
```{r}

d = read.csv("stat_data.csv")

sub = subset(d, Simulation %in% 300:310)
```

## MODELLING
```{r}

# plotting variables to decide on outcome distribution
# Histomancy, this is not a legit procedure. It is the residuals of the model, which are normally distributed or not (282)
ggplot(sub, aes(trade))+geom_density()


# scaling variables
# centering asymmetry and isolation (model is now a lot faster)
# scaling round
sub$Asymmetry_c = scale(sub$Asymmetry, center = T, scale = F)
sub$Isolation_c = scale(sub$Isolation,center = T, scale = F)
sub$Round_s = scale(sub$Round, center = T, scale = T)

prior(normal(0,1), class = b, coef = Round_s)

# brms
get_prior(trade ~ Asymmetry + Isolation + Round, family = poisson(link = "log"), data = sub)


# model with asymmetry and isolation
m1 = brm(trade ~ Asymmetry_c + Isolation_c + Round_s, family = poisson(link = "log"),
         prior = c(prior(normal(0,5), class = Intercept),
                   prior(normal(0,2), class = b, coef = Asymmetry_c),
                   prior(normal(0,2), class = b, coef = Isolation_c),
                   prior(normal(0,1), class = b, coef = Round_s)),
         data = sub,
         cores = 2,
         chain = 1,
         iter = 2000,
         warmup = 1000
         )
summary(m1)
plot(m1)
pp_check(m1)

# model with interaction
m2 = brm(trade ~ Asymmetry_c*Isolation_c*Round_s+(1+Round_s|Simulation), family = poisson(link = "log"),
         prior = c(prior(normal(0,5), class = Intercept),
                   prior(normal(0,2), class = b, coef = Asymmetry_c),
                   prior(normal(0,2), class = b, coef = Isolation_c),
                   prior(normal(0,1), class = b, coef = Round_s),
                   prior(cauchy(0,2), class = sd, group = Simulation),
                   prior(cauchy(0,2), class = sd, coef = Intercept, group = Simulation)),
         data = sub,
         cores = 2,
         chain = 2,
         iter = 2000,
         warmup = 1000
         )

summary(m2)
plot(m2)
pp_check(m2)

# model with only asymmetry
m3 = brm(trade ~ Asymmetry_c, family = poisson(link = "log"),
         prior = c(prior(normal(0,5), class = Intercept),
                   prior(normal(0,1), class = b, coef = Asymmetry_c)),
         data = sub,
         cores = 2,
         chain = 1,
         iter = 1100,
         warmup = 1000
         )

# model with only Isolation
m4 = brm(trade ~ Isolation_c, family = poisson(link = "log"),
         prior = c(prior(normal(0,5), class = Intercept),
                   prior(normal(0,1), class = b, coef = Isolation_c)),
         data = sub,
         cores = 2,
         chain = 1,
         iter = 1100,
         warmup = 1000
         )

# null model
m5 = brm(trade ~ 1, family = poisson(link = "log"),
         prior = c(prior(normal(0,5), class = Intercept)),
         data = sub,
         cores = 2,
         chain = 1,
         iter = 1100,
         warmup = 1000
         )


#  model with round
m6 = brm(trade ~ Round_s, family = poisson(link = "log"),
         prior = c(prior(normal(0,5), class = Intercept),
                   prior(normal(0,1), class = b, coef = Round_s)),
         data = sub,
         cores = 2,
         chain = 1,
         iter = 1100,
         warmup = 1000
         )
summary(m6)


### FULL MODEL - NOW INCLUDING RANDOM EFFECT ###

get_prior(trade ~ Asymmetry_c*Isolation_c*Round_s+(1+Round_s|Simulation), family = poisson(link = "log"), data = sub)

f_m = brm(trade ~ Asymmetry_c*Isolation_c*Round_s+(1+Round_s|Simulation), family = poisson(link = "log"),
         prior = c(prior(normal(0,20), class = Intercept),
                   prior(normal(0,2), class = b, coef = Asymmetry_c),
                   prior(normal(0,2), class = b, coef = Isolation_c),
                   prior(normal(0,1), class = b, coef = Round_s),
                   prior(normal(0,2), class = b, coef = Asymmetry_c:Isolation_c),
                   prior(normal(0,2), class = b, coef = Asymmetry_c:Isolation_c:Round_s),
                   prior(normal(0,2), class = b, coef = Asymmetry_c:Round_s),
                   prior(normal(0,2), class = b, coef = Isolation_c:Round_s)
                   prior(lkj(2), class = cor),
                   prior(cauchy(0,2), class = sd, group = Simulation),
                   prior(cauchy(0,2), class = sd, coef = Intercept, group = Simulation),
                   prior(cauchy(0,2), class = sd, coef =Round_s, group = Simulation)),
         data = sub,
         cores = 1,
         chain = 1,
         iter = 2000,
         warmup = 1000
         )

summary(f_m)
plot(f_)
pp_check(f_m)


# model comparison
# model with interaction outperform the other models
waic(m1,m2,m3,m4,)


```


## PLOTTING
```{r}

ggplot(sub, aes(round, trade))+geom_line()


```


## EXTRA
```{r}

# rethinking
m4 <- map2stan(
  alist(
    trade_s ~ dpois(r) ,
    log(r) <- a + b*diagnosis ,
    a ~ dnorm(0,1),
    b ~ dnorm(0.6,-0.3),
    sigma ~ dcauchy(0,2)
    ), 
  data= dp2)
```

